<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment+, (acronym,expanded-acronym)? , (generic-icon? | glob | magic | treemagic | root-XML | alias | sub-class-of)*)>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!-- a comment describing a document with the respective MIME type. Example: "WMV video" -->
  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>

  <!-- a comment describing the respective unexpanded MIME type acronym. Example: "WMV" -->
  <!ELEMENT acronym (#PCDATA)>
  <!ATTLIST acronym xml:lang CDATA #IMPLIED>

  <!-- a comment describing the respective expanded MIME type acronym. Example: "Windows Media Video" -->
  <!ELEMENT expanded-acronym (#PCDATA)>
  <!ATTLIST expanded-acronym xml:lang CDATA #IMPLIED>

  <!-- a generic icon name as per the Icon Naming Specification, only required if computing
  it from the mime-type would not work, See "generic-icon" in the Shared Mime Specification -->
  <!ELEMENT generic-icon (#PCDATA)>
  <!ATTLIST generic-icon name (application-x-executable|audio-x-generic|font-x-generic|image-x-generic|package-x-generic|text-html|text-x-generic|text-x-generic-template|text-x-script|video-x-generic|x-office-address-book|x-office-calendar|x-office-document|x-office-presentation|x-office-spreadsheet) #IMPLIED>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>
  <!ATTLIST glob weight CDATA #IMPLIED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA #IMPLIED>

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT treemagic (treematch)+>
  <!ATTLIST treemagic priority CDATA #IMPLIED>

  <!ELEMENT treematch (treematch)*>
  <!ATTLIST treematch path CDATA #REQUIRED>
  <!ATTLIST treematch type (file|directory|link) #IMPLIED>
  <!ATTLIST treematch match-case (true|false) #IMPLIED>
  <!ATTLIST treematch executable (true|false) #IMPLIED>
  <!ATTLIST treematch non-empty (true|false) #IMPLIED>
  <!ATTLIST treematch mimetype CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML
  	namespaceURI CDATA #REQUIRED
	localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias
  	type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of
  	type CDATA #REQUIRED>
]>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/andrew-inset">
    <comment>ATK inset</comment>
    <acronym>ATK</acronym>
    <expanded-acronym>Andrew Toolkit</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.ez"/>
  </mime-type>
  <mime-type type="application/epub+zip">
    <comment>electronic book document</comment>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/epub+zip" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.epub"/>
  </mime-type>
  <mime-type type="application/illustrator">
    <comment>Adobe Illustrator document</comment>
    <comment xml:lang="zh_CN">Adobe Illustrator 文档</comment>
    <comment xml:lang="zh_TW">Adobe Illustrator 文件</comment>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.ai"/>
  </mime-type>
  <mime-type type="application/mac-binhex40">
    <comment>Macintosh BinHex-encoded file</comment>
    <comment xml:lang="zh_CN">Macintosh BinHex 编码的文件</comment>
    <comment xml:lang="zh_TW">Macintosh BinHex 編碼檔</comment>
    <generic-icon name="package-x-generic"/>
    <magic priority="50">
      <match value="must be converted with BinHex" type="string" offset="11"/>
    </magic>
  </mime-type>
  <mime-type type="application/mathematica">
    <comment>Mathematica Notebook</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.nb"/>
    <magic priority="50">
      <match value="(************** Content-type: application/mathematica" type="string" offset="0"/>
      <match value="This notebook can be used on any computer system with Mathematica" type="string" offset="100:256"/>
      <match value="This is a Mathematica Notebook file.  It contains ASCII text" type="string" offset="10:256"/>
    </magic>
    <alias type="application/x-mathematica"/>
  </mime-type>
  <mime-type type="application/mbox">
    <comment>mailbox file</comment>
    <generic-icon name="text-x-generic"/>
    <sub-class-of type="text/plain"/>
    <magic priority="20">
      <match value="From " type="string" offset="0"/>
    </magic>
    <glob pattern="*.mbox"/>
  </mime-type>
  <mime-type type="application/octet-stream">
    <comment>unknown</comment>
    <comment xml:lang="zh_CN">未知</comment>
    <comment xml:lang="zh_TW">不明</comment>
    <glob pattern="*.bin"/>
  </mime-type>
  <mime-type type="application/oda">
    <comment>ODA document</comment>
    <comment xml:lang="zh_CN">ODA 文档</comment>
    <comment xml:lang="zh_TW">ODA 文件</comment>
    <acronym>ODA</acronym>
    <expanded-acronym>Office Document Architecture</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.oda"/>
  </mime-type>
  <mime-type type="application/pdf">
    <comment>PDF document</comment>
    <comment xml:lang="zh_CN">PDF 文档</comment>
    <comment xml:lang="zh_TW">PDF 文件</comment>
    <acronym>PDF</acronym>
    <expanded-acronym>Portable Document Format</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="%PDF-" type="string" offset="0"/>
    </magic>
    <glob pattern="*.pdf"/>
    <alias type="application/x-pdf"/>
    <alias type="image/pdf"/>
  </mime-type>
  <mime-type type="application/xspf+xml">
    <comment>XSPF playlist</comment>
    <acronym>XSPF</acronym>
    <expanded-acronym>XML Shareable Playlist Format</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <generic-icon name="audio-x-generic"/>
    <magic priority="50">
      <match value="&lt;playlist version=&quot;1" type="string" offset="0:64"/>
    </magic>
    <glob pattern="*.xspf"/>
  </mime-type>
  <mime-type type="audio/x-gsm">
    <comment>GSM 06.10 audio</comment>
    <acronym>GSM</acronym>
    <expanded-acronym>Global System for Mobile communications</expanded-acronym>
    <glob pattern="*.gsm"/>
  </mime-type>
  <mime-type type="audio/x-iriver-pla">
    <comment>iRiver Playlist</comment>
    <magic priority="50">
      <match value="iriver UMS PLA" type="string" offset="4"/>
    </magic>
    <glob pattern="*.pla"/>
  </mime-type>
  <mime-type type="application/pgp-encrypted">
    <comment>PGP/MIME-encrypted message header</comment>
    <comment xml:lang="zh_CN">PGP/MIME 加密的信件头</comment>
    <comment xml:lang="zh_TW">PGP/MIME 加密訊息標頭</comment>
    <generic-icon name="text-x-generic"/>
    <magic priority="50">
      <match value="-----BEGIN PGP MESSAGE-----" type="string" offset="0"/>
    </magic>
    <glob pattern="*.pgp"/>
    <glob pattern="*.gpg"/>
    <glob pattern="*.asc"/>
    <alias type="application/pgp"/>
  </mime-type>
  <mime-type type="application/pgp-keys">
    <comment>PGP keys</comment>
    <comment xml:lang="zh_CN">PGP 密钥</comment>
    <comment xml:lang="zh_TW">PGP 鑰匙</comment>
    <acronym>PGP</acronym>
    <expanded-acronym>Pretty Good Privacy</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <magic priority="50">
      <match value="-----BEGIN PGP PUBLIC KEY BLOCK-----" type="string" offset="0"/>
      <match value="-----BEGIN PGP PRIVATE KEY BLOCK-----" type="string" offset="0"/>
      <match value="0x9501" type="big16" offset="0"/>
      <match value="0x9500" type="big16" offset="0"/>
      <match value="0x9900" type="big16" offset="0"/>
      <match value="0x9901" type="big16" offset="0"/>
    </magic>
    <glob pattern="*.skr"/>
    <glob pattern="*.pkr"/>
    <glob pattern="*.asc"/>
  </mime-type>
  <mime-type type="application/pgp-signature">
    <comment>detached OpenPGP signature</comment>
    <comment xml:lang="zh_CN">分离的 OpenPGP 签名</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <magic priority="50">
      <match value="-----BEGIN PGP SIGNED MESSAGE-----" type="string" offset="0"/>
      <match value="-----BEGIN PGP SIGNATURE-----" type="string" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/pkcs7-mime">
    <comment>S/MIME file</comment>
    <comment xml:lang="zh_CN">S/MIME 文件</comment>
    <comment xml:lang="zh_TW">S/MIME 檔</comment>
    <generic-icon name="text-x-generic"/>
  </mime-type>
  <mime-type type="application/pkcs7-signature">
    <comment>detached S/MIME signature</comment>
    <comment xml:lang="zh_CN">分离的 S/MIME 签名</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.p7s"/>
  </mime-type>
  <mime-type type="application/pkcs10">
    <comment>PKCS#10 certification request</comment>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.p10"/>
  </mime-type>
  <mime-type type="application/pkix-pkipath">
    <comment>PkiPath certification path</comment>
    <glob pattern="*.pkipath"/>
  </mime-type>
  <mime-type type="application/postscript">
    <comment>PS document</comment>
    <acronym>PS</acronym>
    <expanded-acronym>PostScript</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="\004%!" type="string" offset="0"/>
      <match value="%!" type="string" offset="0"/>
    </magic>
    <glob pattern="*.ps"/>
  </mime-type>
  <mime-type type="application/prs.plucker">
    <comment>Plucker document</comment>
    <generic-icon name="x-office-document"/>
    <magic priority="80">
      <match value="DataPlkr" type="string" offset="60"/>
    </magic>
  </mime-type>
  <mime-type type="application/rtf">
    <comment>RTF document</comment>
    <acronym>RTF</acronym>
    <expanded-acronym>Rich Text Format</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="{\\rtf" type="string" offset="0"/>
    </magic>
    <glob pattern="*.rtf"/>
    <alias type="text/rtf"/>
  </mime-type>
  <mime-type type="application/sieve">
    <comment>Sieve mail filter script</comment>
    <sub-class-of type="application/xml"/>
    <generic-icon name="text-x-script"/>
    <glob pattern="*.siv"/>
  </mime-type>
  <mime-type type="application/smil">
    <comment>SMIL document</comment>
    <acronym>SMIL</acronym>
    <expanded-acronym>Synchronized Multimedia Integration Language</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <alias type="application/smil+xml"/>
    <generic-icon name="video-x-generic"/>
    <glob pattern="*.smil"/>
    <glob pattern="*.smi"/>
    <glob pattern="*.sml"/>
    <glob pattern="*.kino"/>
    <magic priority="55">
      <match value="&lt;smil" type="string" offset="0:256"/>
    </magic>
  </mime-type>
  <mime-type type="application/vnd.ms-wpl">
    <comment>WPL playlist</comment>
    <acronym>WPL</acronym>
    <expanded-acronym>Windows Media Player Playlist</expanded-acronym>
    <generic-icon name="video-x-generic"/>
    <glob pattern="*.wpl"/>
    <magic priority="60">
      <match value="&lt;?wpl" type="string" offset="0:256"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-sqlite2">
    <comment>SQLite2 database</comment>
    <magic>
      <match value="** This file contains an SQLite" type="string" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-sqlite3">
    <comment>SQLite3 database</comment>
    <magic>
      <match value="SQLite format 3" type="string" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-gedcom">
    <comment>GEDCOM family history</comment>
    <acronym>GEDCOM</acronym>
    <expanded-acronym>GEnealogical Data COMmunication</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="0 HEAD" type="string" offset="0"/>
    </magic>
    <glob pattern="*.ged"/>
    <glob pattern="*.gedcom"/>
    <alias type="text/gedcom"/>
  </mime-type>
  <mime-type type="video/x-flv">
    <comment>Flash video</comment>
    <generic-icon name="video-x-generic"/>
    <magic priority="50">
      <match value="FLV" type="string" offset="0"/>
    </magic>
    <glob pattern="*.flv"/>
    <alias type="application/x-flash-video"/>
    <alias type="flv-application/octet-stream"/>
    <alias type="video/flv"/>
  </mime-type>
  <mime-type type="application/x-go-sgf">
    
    <comment>SGF record</comment>
    <acronym>SGF</acronym>
    <expanded-acronym>Smart Game Format</expanded-acronym>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.sgf"/>
    <sub-class-of type="text/plain"/>
    <magic priority="50">
      <match value="(;FF[3]" type="string" offset="0"/>
      <match value="(;FF[4]" type="string" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-xliff">
    <comment>XLIFF translation file</comment>
    <acronym>XLIFF</acronym>
    <expanded-acronym>XML Localization Interchange File Format</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.xlf"/>
    <glob pattern="*.xliff"/>
    <magic priority="80">
      <match value="&lt;xliff" type="string" offset="0:256"/>
    </magic>
    <root-XML namespaceURI='urn:oasis:names:tc:xliff:document:1.1' localName='xliff'/>
  </mime-type>
  <mime-type type="application/vnd.corel-draw">
    <comment>Corel Draw drawing</comment>
    <comment xml:lang="zh_CN">Corel Draw 绘图</comment>
    <comment xml:lang="zh_TW">Corel Draw 繪圖</comment>
    <generic-icon name="image-x-generic"/>
    <magic priority="80">
      <match value="CDRXvrsn" type="string" offset="8" mask="0xffffff00ffffffff"/>
    </magic>
    <glob pattern="*.cdr"/>
    <alias type="application/cdr"/>
    <alias type="application/coreldraw"/>
    <alias type="application/x-cdr"/>
    <alias type="application/x-coreldraw"/>
    <alias type="image/cdr"/>
    <alias type="image/x-cdr"/>
    <alias type="zz-application/zz-winassoc-cdr"/>
  </mime-type>
  <mime-type type="application/vnd.hp-hpgl">
    <comment>HPGL file</comment>
    <acronym>HPGL</acronym>
    <expanded-acronym>HP Graphics Language</expanded-acronym>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.hpgl"/>
  </mime-type>
  <mime-type type="application/vnd.hp-pcl">
    <comment>PCL file</comment>
    <acronym>PCL</acronym>
    <expanded-acronym>HP Printer Control Language</expanded-acronym>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.pcl"/>
  </mime-type>
  <mime-type type="application/vnd.lotus-1-2-3">
    <comment>Lotus 1-2-3 spreadsheet</comment>
    <comment xml:lang="zh_CN">Lotus 1-2-3 工作簿</comment>
    <comment xml:lang="zh_TW">Lotus 1-2-3 試算表</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <magic priority="50">
      <match value="\x00\x00\x02\x00\x06\x04\x06\x00\x08\x00\x00\x00\x00\x00" type="string" offset="0"/>
    </magic>
    <glob pattern="*.123"/>
    <glob pattern="*.wk1"/>
    <glob pattern="*.wk3"/>
    <glob pattern="*.wk4"/>
    <glob pattern="*.wks"/>
    <alias type="application/x-lotus123"/>
    <alias type="application/x-123"/>
    <alias type="application/lotus123"/>
    <alias type="application/wk1"/>
  </mime-type>
  <mime-type type="application/vnd.mozilla.xul+xml">
    <comment>XUL document</comment>
    <acronym>XUL</acronym>
    <expanded-acronym>XML User Interface Language</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.xul"/>
  </mime-type>
  <mime-type type="application/vnd.ms-access">
    <comment>JET database</comment>
    <acronym>JET</acronym>
    <expanded-acronym>Joint Engine Technology</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="\x00\x01\x00\x00Standard Jet DB" type="string" offset="0"/>
    </magic>
    <glob pattern="*.mdb"/>
    <alias type="application/x-msaccess"/>
    <alias type="application/msaccess"/>
    <alias type="application/vnd.msaccess"/>
    <alias type="application/x-msaccess"/>
    <alias type="application/mdb"/>
    <alias type="application/x-mdb"/>
  </mime-type>
  <mime-type type="application/vnd.ms-cab-compressed">
    <comment>Microsoft Cabinet archive</comment>
    <generic-icon name="package-x-generic"/>
    <magic priority="50">
      <match value="MSCF\0\0\0\0" type="string" offset="0"/>
    </magic>
    <glob pattern="*.cab"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel">
    <comment>Excel spreadsheet</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <magic priority="50">
      <match value="Microsoft Excel 5.0 Worksheet" type="string" offset="2080"/>
    </magic>
    <glob pattern="*.xls"/>
    <glob pattern="*.xlc"/>
    <glob pattern="*.xll"/>
    <glob pattern="*.xlm"/>
    <glob pattern="*.xlw"/>
    <glob pattern="*.xla"/>
    <glob pattern="*.xlt"/>
    <glob pattern="*.xld"/>
    <alias type="application/msexcel"/>
    <alias type="application/x-msexcel"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint">
    <comment>PowerPoint presentation</comment>
    <generic-icon name="x-office-presentation"/>
    <glob pattern="*.ppz"/>
    <glob pattern="*.ppt"/>
    <glob pattern="*.pps"/>
    <glob pattern="*.pot"/>
    <alias type="application/powerpoint"/>
    <alias type="application/mspowerpoint"/>
    <alias type="application/x-mspowerpoint"/>
  </mime-type>
  <mime-type type="application/vnd.ms-xpsdocument">
    <comment>XPS document</comment>
    <acronym>XPS</acronym>
    <expanded-acronym>XML Paper Specification</expanded-acronym>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.xps"/>
  </mime-type>
  <mime-type type="application/vnd.ms-works">
    <comment>Microsoft Works document</comment>
    <sub-class-of type="application/x-ole-storage"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.wcm"/>
    <glob pattern="*.wdb"/>
    <glob pattern="*.wks"/>
    <glob pattern="*.wps"/>
  </mime-type>
  <mime-type type="application/msword">
    <comment>Word document</comment>
    <sub-class-of type="application/x-ole-storage"/>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="\x31\xbe\x00\x00" type="string" offset="0"/>
      <match value="PO^Q`" type="string" offset="0"/>
      <match value="\376\067\0\043" type="string" offset="0"/>
      <match value="\333\245-\0\0\0" type="string" offset="0"/>
      <match value="MSWordDoc" type="string" offset="2112"/>
      <match value="MSWordDoc" type="string" offset="2108"/>
      <match value="Microsoft Word document data" type="string" offset="2112"/>
    </magic>
    <glob pattern="*.doc"/>
    <alias type="application/vnd.ms-word"/>
    <alias type="application/x-msword"/>
  </mime-type>
  <mime-type type="application/msword-template">
    <comment>Word template</comment>
    <sub-class-of type="application/msword"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.dot"/>
  </mime-type>
  <mime-type type="application/gnunet-directory">
    <comment>GNUnet search file</comment>
    <magic priority="50">
      <match value="\211GND\r\n\032\n" type="string" offset="0"/>
    </magic>
    <glob pattern="*.gnd"/>
  </mime-type>
  <mime-type type="application/vnd.ms-tnef">
    <comment>TNEF message</comment>
    <acronym>TNEF</acronym>
    <expanded-acronym>Transport Neutral Encapsulation Format</expanded-acronym>
    <magic priority="50">
      <match value="0x223e9f78" type="little32" offset="0"/>
    </magic>
    <glob pattern="*.tnef"/>
    <glob pattern="*.tnf"/>
    <glob pattern="winmail.dat"/>
    <alias type="application/ms-tnef"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.calc">
    <comment>StarCalc spreadsheet</comment>
    <comment xml:lang="zh_CN">StarCalc 工作簿</comment>
    <comment xml:lang="zh_TW">StarCalc 試算表</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <glob pattern="*.sdc"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.chart">
    <comment>StarChart chart</comment>
    <comment xml:lang="zh_CN">StarChart 图表</comment>
    <comment xml:lang="zh_TW">StarChart 圖表</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <glob pattern="*.sds"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.draw">
    <comment>StarDraw drawing</comment>
    <comment xml:lang="zh_CN">StarDraw 绘图</comment>
    <comment xml:lang="zh_TW">StarDraw 繪圖</comment>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.sda"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.impress">
    <comment>StarImpress presentation</comment>
    <comment xml:lang="zh_CN">StarImpress 演示文稿</comment>
    <comment xml:lang="zh_TW">StarImpress 簡報檔</comment>
    <generic-icon name="x-office-presentation"/>
    <glob pattern="*.sdd"/>
    <glob pattern="*.sdp"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.mail">
    <comment>StarMail email</comment>
    <comment xml:lang="zh_CN">StarMail 电子邮件</comment>
    <comment xml:lang="zh_TW">StarMail 郵件</comment>
    <glob pattern="*.smd"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.math">
    <comment>StarMath formula</comment>
    <comment xml:lang="zh_CN">StarMath 公式</comment>
    <comment xml:lang="zh_TW">StarMath 算式</comment>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.smf"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.writer">
    <comment>StarWriter document</comment>
    <comment xml:lang="zh_CN">StarWriter 文档</comment>
    <comment xml:lang="zh_TW">StarWriter 文件</comment>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.sdw"/>
    <glob pattern="*.vor"/>
    <glob pattern="*.sgl"/>
    <magic priority="90">
      <match value="StarWriter" type="string" offset="2089"/>
    </magic>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.calc">
    <comment>OpenOffice Calc spreadsheet</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-spreadsheet"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.sun.xml.calc" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.sxc"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.calc.template">
    <comment>OpenOffice Calc template</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-spreadsheet"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.sun.xml.calc" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.stc"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.draw">
    <comment>OpenOffice Draw drawing</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="image-x-generic"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.sun.xml.draw" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.sxd"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.draw.template">
    <comment>OpenOffice Draw template</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="image-x-generic"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.sun.xml.draw" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.std"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.impress">
    <comment>OpenOffice Impress presentation</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-presentation"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.sun.xml.impress" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.sxi"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.impress.template">
    <comment>OpenOffice Impress template</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-presentation"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.sun.xml.impress" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.sti"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.math">
    <comment>OpenOffice Math formula</comment>
   <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
         <match value="application/vnd.sun.xml.math" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.sxm"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer">
    <comment>OpenOffice Writer document</comment>
   <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.sun.xml.writer" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.sxw"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer.global">
    <comment>OpenOffice Writer global document</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.sun.xml.writer" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.sxg"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer.template">
    <comment>OpenOffice Writer template</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic>
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.sun.xml.writer" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.stw"/>
  </mime-type>
  <mime-type type="application/vnd.oasis.opendocument.text">
    <comment>ODT document</comment>
    <acronym>ODT</acronym>
    <expanded-acronym>OpenDocument Text</expanded-acronym>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.oasis.opendocument.text" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.odt"/>
  </mime-type>
  <mime-type type="application/vnd.oasis.opendocument.text-template">
    <comment>ODT template</comment>
    <acronym>ODT</acronym>
    <expanded-acronym>OpenDocument Text</expanded-acronym>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.oasis.opendocument.text-template" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.ott"/>
  </mime-type>
  <mime-type type="application/vnd.oasis.opendocument.text-web">
    <comment>OTH template</comment>
    <acronym>OTH</acronym>
    <expanded-acronym>OpenDocument HTML</expanded-acronym>
    <sub-class-of type="application/zip"/>
    <generic-icon name="text-html"/>
    <magic priority="50">
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.oasis.opendocument.text-web" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.oth"/>
  </mime-type>
  <mime-type type="application/vnd.oasis.opendocument.text-master">
    <comment>ODM document</comment>
    <acronym>ODM</acronym>
    <expanded-acronym>OpenDocument Master</expanded-acronym>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match value="PK\003\004" type="string" offset="0">
        <match value="mimetype" type="string" offset="30">
          <match value="application/vnd.oasis.opendocument.text-master" type="string" offset="38"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.odm"/>
  </mime-type>